import Web3TransactionTable from "../components/common/Web3TransactionTable";


export default function Table() {
  const transactions = [
    {
        created: '2023-07-15',
        invoice: 'INV-001',
        payee: 'Alice Johnson',
        payer: 'Bob Smith',
        expected: '$150',
        amount: '$150',
        status: 'Completed',
        type: 'getPaid',
      },
      {
        created: '2023-08-03',
        invoice: 'INV-002',
        payee: 'Charlie Brown',
        payer: 'Diana Prince',
        expected: '$300',
        amount: '$275',
        status: 'Partial',
        type: 'pay',
      },
      {
        created: '2023-09-22',
        invoice: 'INV-003',
        payee: 'Eva Green',
        payer: 'Frank Castle',
        expected: '$500',
        amount: '$500',
        status: 'Pending',
        type: 'getPaid',
      },
      {
        created: '2023-10-11',
        invoice: 'INV-004',
        payee: 'George Lucas',
        payer: 'Han Solo',
        expected: '$1000',
        amount: '$1000',
        status: 'Completed',
        type: 'pay',
      },
      {
        created: '2023-11-05',
        invoice: 'INV-005',
        payee: 'Iris West',
        payer: 'John Doe',
        expected: '$75',
        amount: '$0',
        status: 'Overdue',
        type: 'getPaid',
      },
      {
        created: '2023-12-18',
        invoice: 'INV-006',
        payee: 'Kate Bishop',
        payer: 'Loki Laufeyson',
        expected: '$250',
        amount: '$250',
        status: 'Completed',
        type: 'pay',
      },
      {
        created: '2024-01-09',
        invoice: 'INV-007',
        payee: 'Mary Jane',
        payer: 'Natasha Romanoff',
        expected: '$180',
        amount: '$180',
        status: 'Pending',
        type: 'getPaid',
      },
      {
        created: '2024-02-27',
        invoice: 'INV-008',
        payee: 'Oliver Queen',
        payer: 'Peter Parker',
        expected: '$420',
        amount: '$400',
        status: 'Partial',
        type: 'pay',
      },
      {
        created: '2024-03-14',
        invoice: 'INV-009',
        payee: 'Quentin Beck',
        payer: 'Reed Richards',
        expected: '$600',
        amount: '$600',
        status: 'Completed',
        type: 'getPaid',
      },
      {
        created: '2024-04-01',
        invoice: 'INV-010',
        payee: 'Steve Rogers',
        payer: 'Tony Stark',
        expected: '$5000',
        amount: '$0',
        status: 'Overdue',
        type: 'pay',
      },
    
    // Add more transactions as needed
    
        {
          created: '2024-04-05',
          invoice: 'INV-011',
          payee: 'Bruce Wayne',
          payer: 'Clark Kent',
          expected: '$1000',
          amount: '$1000',
          status: 'Completed',
          type: 'getPaid',
        },
        {
          created: '2024-04-10',
          invoice: 'INV-012',
          payee: 'Diana Prince',
          payer: 'Arthur Curry',
          expected: '$750',
          amount: '$500',
          status: 'Partial',
          type: 'pay',
        },
        {
          created: '2024-04-15',
          invoice: 'INV-013',
          payee: 'Barry Allen',
          payer: 'Hal Jordan',
          expected: '$300',
          amount: '$0',
          status: 'Overdue',
          type: 'getPaid',
        },
        {
          created: '2024-04-20',
          invoice: 'INV-014',
          payee: 'Victor Stone',
          payer: 'Billy Batson',
          expected: '$450',
          amount: '$450',
          status: 'Pending',
          type: 'pay',
        },
        {
          created: '2024-04-25',
          invoice: 'INV-015',
          payee: 'Selina Kyle',
          payer: 'Harley Quinn',
          expected: '$200',
          amount: '$200',
          status: 'Completed',
          type: 'getPaid',
        },
        {
          created: '2024-05-01',
          invoice: 'INV-016',
          payee: 'Barbara Gordon',
          payer: 'Dick Grayson',
          expected: '$600',
          amount: '$600',
          status: 'Completed',
          type: 'pay',
        },
        {
          created: '2024-05-05',
          invoice: 'INV-017',
          payee: 'Jason Todd',
          payer: 'Tim Drake',
          expected: '$350',
          amount: '$0',
          status: 'Overdue',
          type: 'getPaid',
        },
        {
          created: '2024-05-10',
          invoice: 'INV-018',
          payee: 'Damian Wayne',
          payer: 'Alfred Pennyworth',
          expected: '$100',
          amount: '$100',
          status: 'Completed',
          type: 'pay',
        },
        {
          created: '2024-05-15',
          invoice: 'INV-019',
          payee: 'Kara Danvers',
          payer: 'James Olsen',
          expected: '$550',
          amount: '$400',
          status: 'Partial',
          type: 'getPaid',
        },
        {
          created: '2024-05-20',
          invoice: 'INV-020',
          payee: 'Lena Luthor',
          payer: 'Cat Grant',
          expected: '$800',
          amount: '$800',
          status: 'Pending',
          type: 'pay',
        },
        {
          created: '2024-05-25',
          invoice: 'INV-021',
          payee: 'Oliver Queen',
          payer: 'Felicity Smoak',
          expected: '$250',
          amount: '$250',
          status: 'Completed',
          type: 'getPaid',
        },
        {
          created: '2024-06-01',
          invoice: 'INV-022',
          payee: 'John Diggle',
          payer: 'Thea Queen',
          expected: '$400',
          amount: '$300',
          status: 'Partial',
          type: 'pay',
        },
        {
          created: '2024-06-05',
          invoice: 'INV-023',
          payee: 'Roy Harper',
          payer: 'Dinah Lance',
          expected: '$150',
          amount: '$0',
          status: 'Overdue',
          type: 'getPaid',
        },
        {
          created: '2024-06-10',
          invoice: 'INV-024',
          payee: 'Cisco Ramon',
          payer: 'Caitlin Snow',
          expected: '$500',
          amount: '$500',
          status: 'Completed',
          type: 'pay',
        },
        {
          created: '2024-06-15',
          invoice: 'INV-025',
          payee: 'Harrison Wells',
          payer: 'Joe West',
          expected: '$700',
          amount: '$700',
          status: 'Pending',
          type: 'getPaid',
        },
        {
          created: '2024-06-20',
          invoice: 'INV-026',
          payee: 'Wally West',
          payer: 'Jesse Quick',
          expected: '$300',
          amount: '$300',
          status: 'Completed',
          type: 'pay',
        },
        {
          created: '2024-06-25',
          invoice: 'INV-027',
          payee: 'Ralph Dibny',
          payer: 'Sue Dearbon',
          expected: '$450',
          amount: '$300',
          status: 'Partial',
          type: 'getPaid',
        },
        {
          created: '2024-07-01',
          invoice: 'INV-028',
          payee: 'Jefferson Pierce',
          payer: 'Lynn Stewart',
          expected: '$600',
          amount: '$0',
          status: 'Overdue',
          type: 'pay',
        },
        {
          created: '2024-07-05',
          invoice: 'INV-029',
          payee: 'Anissa Pierce',
          payer: 'Jennifer Pierce',
          expected: '$200',
          amount: '$200',
          status: 'Completed',
          type: 'getPaid',
        },
        {
          created: '2024-07-10',
          invoice: 'INV-030',
          payee: 'Gambi',
          payer: 'Tobias Whale',
          expected: '$1000',
          amount: '$1000',
          status: 'Pending',
          type: 'pay',
        }
      
  ];

  return (
    // <div className="container  py-8">
    //   {/* <h1 className="text-3xl font-bold text-center mb-8">Web3 Transactions</h1> */}
    //   <Web3TransactionTable transactions={transactions} />
    // </div>
     <Web3TransactionTable transactions={transactions} />
);
}